.\" -*- nroff -*-
.\" Copyright 2011 by Paulino Ruiz de Clavijo. All Rights Reserved.
.\" This file may be copied under the terms of the GNU Public License.
.\"
.TH "nanofs.dump "1" "may 2016" "" ""
.SH "NAME"
nanofs.dump \(em a tool to dump nanofs structure
.SH "SYNOPSIS"

.B nanofs-dump
[OPTIONS] [FILE/DEVICE] 

.SH "OPTIONS"
.TP
\fB-c\fP
Dump file contents

.SH "DESCRIPTION"

.B nanofs.dump
is a command line tool to dump to stdout nanoFS internal structure
for debug purpose

.PP 
.SH "CREDITS"

.PP 
NanoFS is distributed under the GNU public license version 3.  See the file
COPYING for details.

.SH "AUTHOR"

.B NanoFS
has been developed by Paulino Ruiz de Clavijo <paulino@dte.us.es>.


.SH BUGS
Please, report them to the author.
.SH AVAILABILITY
.B nanofs.dump
is part of the NanoFS project available at 
https://github.com/paulino/nanofs-fuse
.SH SEE ALSO
.BR mkfs.nanofs (8)
